#+title: Ap Chem Summer Assignment #3
#+author: Shaurya Singh
#+startup: preview
#+startup: fold
#+options: toc:nil
#+latex_class: chameleon
#+latex_header: \usepackage{chemfig}
#+latex_header: \usepackage[version=4]{mhchem}
#+latex_header: \usepackage{enumerate}

* The following reaction was performed, Identify element X.
\begin{align*}
  &\ce{Fe2O_3(s)+2X(s)} = \ce{2Fe(s)+X_2O_3(s)}\\
  &79.947g+2x=55.847g+50.982g\\
  &2x=106.829g-79.847g\\
  &2x=26.982g\\
\end{align*}
Since the atomic weight of \(\ce{2Fe}\) is the same as the given weight
(\(55.847g\)), the atomic weight of 2x is \(26.982g\) or Aluminium (\(\ce{Al}\))

* Balance the following equations
a. \(\ce{2AgI+Na2S} \rightarrow \ce{2Ag2S+NaI}\)
b. \(\ce{(NH4)2Cr2O7} \rightarrow \ce{Cr2O3+N2+4H2O}\)
c. \(\ce{Na3PO4+3HCl} \rightarrow \ce{3NaCl+H3PO4}\)
d.  \(\ce{TiCl4+2H2O} \rightarrow \ce{TiO2+4HCl}\)
e.  \(\ce{Ba3N2+6H2O} \rightarrow \ce{3Ba(OH)2+2NH3}\)
f.  \(\ce{3HNO2+HNO3} \rightarrow \ce{2NO+H2O}\)

* Balance the following equation:
\(\ce{4NH4OH(aq)+KAI(SO)4\cdot12H2O}=\ce{Al(OH)3(s)+2(NH4)2Cr2O7+KOH(aq)+12H2O}\)
We can multiple \(\ce{NH4OH}\) by 4, and increase NH4 and H2O on the product
side to compensate

* Balance the following equation
\(\ce{2Fe+6HC2H3O2}=\ce{2Fe(C2H3O2)3+3H2}\)

* How many grams of water vapor can be generated from the combustion of 18.74 g of ethanol (C 2 H 6 O)?

* How many grams of potassium iodide are necessary to completely react with 20.61g of Mercury (II) chloride
First we balance the equation
\(\ce{HgCl2+2KL}=\ce{HgI2+2KCl}\)
Next we to find the total atomic weight.
\(200.59+2(35.45)+2(39.10+126.90)\)
Afterwards, we calculate the ratio needed
\(\frac{332}{271.49}=1.22\)
Finally we multiply
\(20.61*1.22=25.203\)

* How many grams of water vapor can be generated from the combustion of 18.74 g of ethanol (C 2 H 6 O)?

* A reaction combines 64.81 grams of silver nitrate with 92.67 grams of potassium bromide
a. 72g
b. \(\ce{AgNO3}\) is the limiting reactant
c. 47.3g
d. 20.5%

* The moleculer weight of an insecticide, dibromoethane, is 187.9. Its molecular formula is \(\ce{C2H2Br2}\), What percent by mass of bromine does dibromoethane contain?
C = 12.011
H = 1.008
Br = 79.90

\(\ce{C2H4Br2}\)

= 24.022 + 4.032 + 159.8
= 187.9
=159.8/187.9
=.8505

= %85.05

* A given sample of xenon fluoride contains molecules of a single type of \(\ce{XeFn}\), where n is some whole number. Given that \(9.03*10^{20}\)

moles = \(9.03*10^{20}/6.022*10^{23}\) = 1.5*10^-3
= 0.31
0.31/131+19n = 186,5 + 23.5n = 310
n = 4
therefore its \(\ce{XeF4}\)

* Molar mass of KCIO

k = 39.0983
Cl = 35.45
O = 16.00

39.0983 + 35.45 + 3*16 = 122.55g
6.32/122.55 = 6.052 moles
2 mol KClO3 = 3 mol O2
2 = 3
0.052*3/2
= 0.078 mol

* The equation (balanced) is
\(\ce{Ca(OH)2+2HCl}=\ce{CaCl2 + 2H2O}\)

Therefore the coeffecient is 2

* the answer is
1

* The answer is
\(\ce{2CHCl3 + 2Cl2}=\ce{2CCl4+2HCl}\)

\(\ce{CHCl3=}\) 119.378
\(\ce{CCl4=}\) 153.823

Theoretical mass = 153.823 * 0.097 = 15.336g
% yield = 12.6/15.336 = %82.16

* The answer is
Ch4 is the limiting reactant
8x 1 mol Ch4 / 16.04 g/mol = .499

.499 * 153.82 = 76.72g

* The answer is
sodium carbonate + hydrohloric acid = sodium chloride + carbon doxide + water
= \(\ce{Na2CO3+HCl}+\ce{NaCl + CO2 + H2O}\)
= \(\ce{Na2CO3+2HCl}+\ce{2NaCl + 2CO2 + H2O}\)

* The answer is
a. \(\ce{NaOH + KNO3}=\ce{NaNO3+KOH}\) = double replacement
b. \(\ce{CH4+2O2}=\ce{}\) = combustion
c. \(\ce{Fe + 3NaBr}=\ce{FaBr2+3Na}\) = single replacement
d. already balanced, double replacement
e. already balanced, double replacement
f. already balanced, synthesis
g. already balanced, decomposition

* The answers are
a. Ba(OH)2 -> BaO+H2O
b. Na2CO3 -> Na2O +CO2
c. 2LiCLI3 -> 2LiCL + 3O2
d. Al2O3 -> 2AL2 + O3
e. H2SO4 -> H2O + SO3

* The answers are
a. 2Mg + O2 = 2MgO
b. N2 + 3H2 = 2NH3
c. S + O2 = SO2
d. CaO + H2O -> Ca(OH)2

* The answers are
a. 2H2O2 -> 2H2O + O2
b. Cu2+ + So42- + Ba2+ - 20H- -> Cu (OH)2 + BaSO4
c. Al+3Ag+ -> Al3+ + 3Ag
d. Cl2 + 2NaBr -> Br2 + 2NaCl
e. C2H6 + 3O2 -> CO2 + CO + 3H2O

* The answers are
Part A:
1. Soluble
2. Insoluble
3. Insoluble
4. Insoluble
5. Soluble
6. Insoluble
7. Insoluble
8. Insoluble
9. Soluble
10 Insoluble.
11. Insoluble
12. Soluble
13. Soluble
14. Soluble
15. Insoluble
16. Insoluble

Part B:
1. \(\ce{AgBr(s)\ KNO3(aq)}\)
      \(\ce{BaBr2(aq)\ KCl(aq)}\)
      \(\ce{AlBr3(aq)\ KNO3(aq)}\)
      \(\ce{K2SO4(aq)\ CuBr2(aq)}\)

2. \(\ce{Ag2CO3(s)\ KNO3(aq)}\)
      \(\ce{NaCl(aq)\ KCl(aq)}\)
      \(\ce{Al2(CO3)3(s)\ KNO3(aq)}\)
      \(\ce{CuCO3(s)\ CuBr2(aq)}\)

3. \(\ce{Ag2S(s)\ KNO3(aq)}\)
      \(\ce{CaCl(aq)\ KCl(aq)}\)
      \(\ce{AlBr3(aq)\ KNO3(aq)}\)
      \(\ce{K2SO4(aq)\ CuBr2(aq)}\)

4. \(\ce{AgOH(s)\ KNO3(aq)}\)
      \(\ce{Ba(OH)2(aq)\ KCl(aq)}\)
      \(\ce{Al(OH)3(aq)\ KNO3(aq)}\)
      \(\ce{NH4(SO4)2(aq)\ CuBr2(aq)}\)

* The answers are
1. \(\ce{CH4}\) - methane
2. \(\ce{C3H8}\) - propane
3. \(\ce{C4H8}\) - butene
4. \(\ce{C4H8}\) - butyne

5. Ethane \(\ce{C2H}\) (c-c)
6. Methane \(\ce{CH4}\) (c-c)
7. Propyne \(\ce{C3H4}\) (c---c)
8. 2 \cdot Butene \(\ce{2C4H8}\) (c---c)
