#+title: Ap Chem Summer Assignment #3
#+author: Shaurya Singh
#+startup: preview
#+startup: fold
#+options: toc:nil
#+latex_class: chameleon
#+latex_header: \usepackage{chemfig}
#+latex_header: \usepackage[version=4]{mhchem}
#+latex_header: \usepackage{enumerate}


* The following reaction was performed, Identify element X.
\begin{align*}
  &\ce{Fe2O_3(s)}+\ce{2X(s)} = \ce{2Fe(s) + X_2O_3(s)}\\
  &79.847g+2x=55.847g+50.982g\\
  &\Rightarrow\ 2x=106.829g-79.847g\\
  &\Rightarrow\ 2x=26.982g\\
\end{align*}

Since the atomic weight of \(\ce{Fe}\) is proportional to the given weight
(\(55.847g\)), the atomic weight of X is equally proportional to the derived
weight (\(26.982g\)). *Therefore, the element is Aluminium (\(\ce{Al}\)).*

* Fill in the blanks to balance the following chemical equations:
#+attr_latex: :options [a.]
a. \(\ce{2AgI + Na2S} \rightarrow \ce{Ag2S + 2NaI}\)
b. \(\ce{(NH4)2Cr2O7} \rightarrow \ce{Cr2O3}+\ce{N2}+\ce{4H2O}\)
c. \(\ce{Na3PO4}+\ce{3HCl} \rightarrow \ce{3NaCl}+\ce{H3PO4}\)
d. \(\ce{TiCl4}+\ce{2H2O} \rightarrow \ce{TiO2}+\ce{4HCl}\)
e. \(\ce{Ba3N2}+\ce{6H2O} \rightarrow \ce{3Ba(OH)2}+\ce{2NH3}\)
f. \(\ce{3HNO2} \rightarrow \ce{HNO3}+\ce{2NO}+\ce{H2O}\)

* Balance the following equation:
We can multiple \(\ce{NH4OH}\) by 4, and increase NH4 and H2O on the product
side to compensate

*Balanced equation*:

\(\ce{4NH4OH(aq) + KAl(SO4)2} \cdot \ce{12H2O(s)} = \ce{Al(OH)3(s)} +
\ce{2(NH4)2Cr2O7 + KOH(aq)} + \ce{12H2O(l)}\)

* Balance the following equation
We need to increase the number of acetate ions on the right side to match the
ones on the left. We also need to increase the right hand side to match the
number of hydrogen atoms on the left.

*Balanced equation*:
\(\ce{2Fe(s)}+\ce{6HC2H3O2(aq)}=\ce{2Fe(C2H3O2)3(aq)}+\ce{3H2(g)}\)

* How many grams of water vapor can be generated from the combustion of 18.74 g of ethanol (C 2 H 6 O)?
Balanced reaction:
\(\ce{C2H6O(g) + 3O2(g)} \rightarrow \ce{C2O2(g) + 3H2O(g)}\)

Given: ethanol ($\ce{C2H6O}$) =  18.74 g

To be calculated : gms of water vapour (H2O) generated after combustion

*Calculating how many mol of ethanol we have:*

Molar mass of ethanol = 46.07 g/mol

Mass(g) of ethanol = 18.74g

Mol = Mass in grams(g) / molar mass (g/mol)

\begin{align*}
mol&=18.74/46.07\\
&=.4068\\
\end{align*}

*Multiply this by the ratio of H2O produced from the combustion of ethanol 3 H2O molecules were produced from 1 C2H6O molecule*
\begin{align*}
\text{mol of H2O}&=\text{mol of C2H6O} * (\text{molecules produced of H2O}/\text{molecules of reactant of C2H6O})\\
&=0.4068mol \times (3/1)\\
&=1.22mol
\end{align*}

*Convert mol back to grams*

Mass(g) / molar mass(g/mol) = # of mol

Mass(g) = # of mol * molar mass(g/mol)

\begin{align*}
\text{Mass of H2O(g)}&=1.22mol * 18.015(g/mol)\\
&= 21.99g
\end{align*}

*Therefore, we will get 21.99g of water vapor*

* How many grams of potassium iodide are necessary to completely react with 20.61g of Mercury (II) chloride
Balance the equation:
\(\ce{HgCl2 + 2KI(aq)} \rightarrow \ce{HgI2(s) + 2KCl(aq)}\)

*Find the molar mass of HgCl and 2KI (g/mol)*

$\ce{HgCl2} = 200.59 + 2(35.45)$

$= 271.49$

$\ce{2KI} = 2(39.10 + 126.90)$

$= 332$

*We calculate the ratio of KI to HgCl2*

Ratio = 2KI/HgCl2

$= 332/271.49$

$= 1.22$

Multiply this by the amount of HgCl2 used to get the amount of Potassium Iodide
needed

$20.61 \cdot 1.22 = 25.20g$

*Therefore, 25.20g of Potassium Iodide is needed*

* A reaction combines 113.484 g of lead (II) nitrate with 45.010 g of sodium hydroxide (NaOH[aq]).
The equation for the reaction is
\(\ce{Pb(NO3)2}+\ce{2NaOH}\rightarrow\ce{Pb(OH)2}+\ce{2NaNO3}\)

The molecules molar mass's are

\(\ce{Pb(OH)2}=241.196 amu\)

\(\ce{Pb(NO3)2}=331.207 amu\)

\(\ce{2NaOH}=79.94 amu\)

\(\ce{2NaNO3}=169.99 amu\)

#+attr_latex: :options [a.]
1. We know that $331.207$ amu of  lead nitrate can react with $79.94$ amu of sodium
   hydroxide. Therefore, $113.484g$ of lead nitrate will react with
   $\frac{113.484*79.94}{331.207}g$, or $27.41g$ of sodium hydroxide

   Similarly, we know that $331.207$ amu of  lead nitrate can produce $241.196$ amu of lead
   hydroxide. Therefore, $113.484g$ of lead nitrate will produce
   $\frac{113.484*241.196}{331.207}g$, or $82.643g$ of lead hydroxide
2. From the above we can see the limiting reactant is lead (II) nitrate and the excess reactant left over is sodium hydroxide.
3. There is $45.010-27.408=17.602$ grams of the excess reactant left over.
4. From the above we get an experimental yield of $80.02$ percent. We know the
   limiting reactant gives us a theoretical yield of $82.463$ percent.
   Therefore, the percent yield is    \((\frac{80.02}{82.463}\times100=97.04)\), or 97.04%

* A reaction combines 64.81 grams of silver nitrate with 92.67 grams of potassium bromide
*The equation for the reaction is already balanced:*
\(\ce{AgNO3}+\ce{KBr}\rightarrow\ce{AgBr}+\ce{KNO3}\)

#+attr_latex: :options [a.]
1. Calculate the atomic weight of the reactants and \(\ce{AgBr}\):

  \(\ce{AgNO3} = 169.872g\)

  \(\ce{Kbr} = 119.002g\)

  \(\ce{AgBr} = 187.772g\)

  Now we can calculate how much \(\ce{AgBr}\) each reactant made

  \(\ce{AgNO3}\): \(\frac{64.81\times187.772g}{169.872}=71.64g\)

  \(\ce{KBr}\): \(\frac{92.67\times187.772g}{119.002}=146.2g\)

2. \(\ce{AgNO3}\) is the limiting reactant since it produces the least amount of
   \(\ce{AgBr}\). Therefore the excessive reactant is  \(\ce{Kbr}\) since it
   produced the most amount of AgBr
3. To calculate how much excessive reactant is left over, we can use the
   theoretical yield and find the mass of the excessive reactant used:

   \(\frac{71.64\times119.002g}{187.772}=45.40\), or $45.40g$ of KBr
4. In order to find the percent yeild, divide the actual yield by the
   theoretical yield, then multiply by 100:

   \(\frac{14.77g}{71.64g}\times100=20.62\), or $20.62$ percent.

* The moleculer weight of an insecticide, dibromoethane, is 187.9. Its molecular formula is \(\ce{C2H4Br2}\), What percent by mass of bromine does dibromoethane contain?
*We must calculate the atomic weight for each element*
\begin{align*}
&\ce{C} = 12.011\\
&\ce{H} = 1.008\\
&\ce{Br} = 79.90
\end{align*}

Since the formula is  \(\ce{C2H4Br2}\), we can substitute the atomic weights in
place of the elements
\begin{align*}
&= 2(\ce{C}) + 4(\ce{H}) + 2(\ce{Br})\\
&= 2(12.011) + 4(1.008) + 2(79.90)\\
&= 24.022 + 4.032 + 159.8\\
&= 187.9
\end{align*}

Finally, we need to divide the amount of bromine by the total amount in order to
find the percent by mass of bromine in \(\ce{C2H4Br2}\)
\begin{align*}
&= \frac{159.8}{187.9}\\
&=.8505
\end{align*}

*Therefore, dibromoethane contains 85.05% by mass of bromine.*

* A given sample of xenon fluoride contains molecules of a single type of \(\ce{XeFn}\), where n is some whole number.
First, we need to calculate how many moles of xenon fluoride there are, and
calculate its weight

\begin{align*}
moles&=9.03*10^{20}/6.022*10^{23}\\
&= 1.5*10^-3\\
&= 0.31g
\end{align*}

Now, we can calculate for $n$

\begin{align*}
&= 0.31/131+19n\\
&= 186.5 + 23.5n = 310\\
&n = 4
\end{align*}

*Therefore its formula is \(\ce{XeF4}\)*

* A 6.32 g sample of potassium chlorate was decomposed according to the following equation, how many moles were formed?
We have the following values:
\begin{align*}
&k = 39.0983g\\
&Cl = 35.45g\\
&O = 16.00g
\end{align*}

From there we can calculate the total molar mass
\begin{align*}
&39.0983 + 35.45 + 3*16 = 122.55g
\end{align*}

Now, by performing dimensional analysis we get the following equation to convert
grams of potassium chlorate to moles of oxygen
\begin{align*}
  \text{mol}&=\frac{6.32g}{1}\times\frac{1mol}{122.548g}\times\frac{3}{2}\\
  &=\frac{6.32g*3}{(122.648*2)}\\
  &=7.74*10^{-2}\\
\end{align*}

*Therefore, \(7.74*10^{-2}\) moles of \(\ce{O2}\) is formed*

* What is the coefficient in front of water, when it is produced from the reaction of hydrochloric acid with calcium hydroxide? Calcium chloride is the other product.
The balanced equation is
\(\ce{Ca(OH)2+2HCl}=\ce{CaCl2 + 2H2O}\)

*Therefore the coeffecient of water (\(\ce{H2O}\) is 2*

* What is the subscript of aluminum in the formula of aluminum phosphate?
*Aluminum has a subscript of $1$ in \(\ce{AlPO4}\)*

* The reaction of 11.9 g of CHCl 3 with excess chlorine produced 12.6 g of CCl 4 , carbon tetrachloride, what is the percent yield?
The equation for the reaction is
\(\ce{2CHCl3 + 2Cl2}=\ce{2CCl4 + 2HCl}\)

We need to calculate the theoretical yield of this reaction. To do that, we need
to calculate the atomic weight of \(\ce{CHCl3}\) and \(\ce{CCl4}\).

\(\ce{ChCl3}\): \(119.378g\)

\(\ce{CCL4}\): \(153.823g\)

Now we can find the theoretical yield:
\begin{align*}
  &=\frac{11.9g}{1}\times\frac{1mol}{119.378g}\times\frac{2}{2}\times\frac{153.823g}{1}\\
  &=\frac{11.9*2*153.823g}{(119.378*2)}\\
  &=15.3g\\
\end{align*}

To find the percent yield, divide the experimental yield by the theoretical
yield, then multiply by 100
\begin{align*}
  &=\frac{12.6g}{15.3g}\times100\\
  &=82.4\\
\end{align*}

*Therefore the percent yield is 82.4%*

* What mass of CCl 4 is formed by the reaction of 8.00 g of methane with an excess of chlorine? Ch4 is the limiting reactant
The given equation is already balanced. The question is asking us to calculate
the theoretical yield

We need to calculate the atomic weight of \(\ce{CCl4}\) and \(\ce{CH4}\)

\(\ce{CCl4}\): \(153.823g\)

\(\ce{CH4}\): \(16.043g\)

Using dimensional analysis, we can calculate the theoretical yield
\begin{align*}
&=\frac{8.00g}{1}\times\frac{1}{16.043g}\times \frac{1}{1}\times \frac{153.823g}{1}\\
&=\frac{8 \times 153.823g}{16.043}\\
&=76.7g\\
\end{align*}

*Therefore, $76.72g$ of \(\ce{CCl4}\) is formed by the reaction.*

* A reaction occurs between sodium carbonate and hydrochloric acid producing sodium chloride, carbon dioxide, and water. Write the balanced chemical equation for the reaction.
The equation will be sodium carbonate + hydrohloric acid = sodium chloride +
carbon doxide + water. In correct notation this is written as:

\begin{align*}
&\ce{Na2CO3 + HCl}+\ce{NaCl + CO2 + H2O}
\end{align*}

Balanced, this equation is
\begin{align*}
&\ce{Na2CO3 + 2HCl}+\ce{2NaCl + 2CO2 + H2O}
\end{align*}

* Classify the type of reaction from the five major type of reactions you learned in your first year chemistry course and write word equations. If necessary, balance.
#+attr_latex: :options [a.]
1. This equation is already balanced, and is a double replacement reaction since
   the two positive ions switched the negative ions they are bonded with.
2. \(\ce{CH4 + 2O2}=\ce{CO2 + 2H2O}\) is a combustion reaction. since
   \(\ce{CH4}\) reacted with oxygen gas.
3. \(\ce{Fe + 3NaBr}=\ce{FaBr2 + 3Na}\) is a single replacement reaction since
   the negative ion in the reactants switches the positive ion its bonded with.
4. This equation is already balanced, and is a double replacement reaction since
   the two positive ions switched the negative ions they are bonded with. The
   equation was already balanced out
5. This equation is already balanced, and is a double replacement reaction since
   the two positive ions switched the negative ions they are bonded with. The
   equation was already balanced out
6. This equation is already balanced, and is a synthesis reaction since the two
   reactants combined to form one product.
7. This equation is already balanced, and is a decomposition reaction since a
   compound (in this case the reactant) breaks down

* Now try these recation types, Rewrite as a balanced equation with the products predicted
#+attr_latex: :options [a.]
1. \(\ce{Ba(OH)2}\rightarrow\ce{BaO + H2O}\)
2. \(\ce{Na2CO3}\rightarrow\ce{Na2O + CO2}\)
3. \(\ce{2LiClO3}\rightarrow\ce{2LiCl + 3O2}\)
4. \(\ce{2Al2O3}\rightarrow\ce{4Al2 + 3O2}\)
5. \(\ce{H2SO4}\rightarrow\ce{H2O + SO3}\)

* Now try these recation types, Rewrite as a balanced equation with the products predicted
#+attr_latex: :options [a.]
1. \(\ce{2Mg + O2}\rightarrow\ce{2MgO}\)
2. \(\ce{N2 + 3H2}\rightarrow\ce{2NH3}\)
3. \(\ce{S + O2}\rightarrow\ce{SO2}\)
4. \(\ce{CaO + H2O}\rightarrow\ce{Ca(OH)2}\)

* Attempt to write and predict products the following chemical reactions:
#+attr_latex: :options [a.]
1. \(\ce{2H2O2}\rightarrow\ce{2H2O + O2}\)
2. \(\ce{Ba(OH)2 + CuSO4}\rightarrow\ce{Cu(OH)2 + BaSO4}\)
3. \(\ce{Al + 3AgNO3}\rightarrow\ce{Al(NO3)3 + + 3Ag}\)
4. \(\ce{Cl2 + 2NaBr}\rightarrow\ce{Br2 + 2NaCl}\)
5. \(\ce{2C2H6 + 7O2}\rightarrow\ce{4CO2 + 6H2O}\)

* Using the solubility rules table, classify each of the substances as being soluble or insoluble in water. Then, Identify the two new compounds that form if the solutions, as suggested by the following table, were mixed via a double displacement reaction.
** Part A
#+attr_latex: :options [a.]
1.  \(\ce{KBr}\) = Soluble. Based on the soluble salt rules, bromine anions are
   soluble when bonded with a cation that isn't \(\ce{Pb}\), \(\ce{Ag}\),
   or \(\ce{Hg2+}\). This means that \(\ce{Kbr}\) is soluble.
2.  \(\ce{PbCO3}\) = Insoluble. Since \(\ce{Pb}\) isn't from group 1 and there
   aren't any rules for \(\ce{CO3}\), \(\ce{PBCO3}\) is insoluble.
3.  \(\ce{BaSO4}\) = Insoluble. Based on the soluble salt rules, when
   \(\ce{SO4}\) is bonded with Ba, it makes it insoluble
4.  zinc hydroxide = Insoluble. \(\ce{Zn(OH)2}\) is amphateric but it isn't a
   strong acid or a strong base, so its insoluble
5.  sodium acetate = Soluble. \(\ce{NaCH3COO}\) is soluble since the cation is
   from the first group of the periodic table and the anion is the polyatomic
   ion acetate, both of whitch are always soluble in a compound
6.  silver iodide = Insoluble. \(\ce{AgI}\) is insoluble since the rules of
   soluble salts state that when the anion I is in a compound with Ag, then it
   is insoluble
7.  cadmium (II) sulfide = Insoluble. \(\ce{CdS}\) is insoluble since there is
   no rule written about sulfur anions nor cadmium. Cadmium also isn't a group 1
   element, making the compound insoluble
8.  zinc carbonate = Insoluble. \(\ce{ZNCO3}\) is insoluble since there is no
   rule written about carbonate polyatomic anions. Zinc also isn't a group 1 element
9.  silver acetate = Soluble. \(\ce{AgC2H3O2}\) is soluble since the compound
   countains an acetate  polyatomic anion. The soluble salt rule states that any
   compound with acetate should be soluble
10. copper (II) sulfide = Insoluble. \(\ce{CuS}\) is insoluble since neither or
    copper nor sulfur is included in the soluble salt rules. Copper also isn't a
    group 1 element, so the compound is insoluble
11. \(\ce{Mg3(PO4)2}\) = Insoluble. Phosphate is not mentioned in the soluble
    salt rules, and magnesium isn't a group one element, so this compound is insoluble
12. \(\ce{KOH}\) = Soluble. It is in the list of the 8 strong bases
13. \(\ce{NiCl2}\) = Soluble. The soluble salt rule states that when a compound
    contains chlorine as anion, as long as the cation it is bonded to isn't
    \(\ce{Pb}\),     \(\ce{Ag}\), or \(\ce{Hg2^{2+}}\) it will be a soluble
    compound.
14. \(\ce{NH4OH}\) = Soluble. \(\ce{NH4OH}\) contains \(\ce{NH4}\), and based on
    the soluble salt rules, the compound containing it is soluble.
15. \(\ce{Hg2SO4}\) = Insoluble. The soluble salt rules state when sulfate is
    bonded with     \(\ce{Hg2}\) in a compound, it renders it insoluble
16. \(\ce{PbI2}\) = Insoluble. The soluble salt rule states that when the anion
    iodine is bonded to the cation lead, it will be insoluble

** Part B
|-------------------------------------+-------------------------------------------+------------------------------------------+---------------------------------------------|
| _\(\ce{AgBr(s)}\),_ \(\ce{KNO3(aq)}\) | _\(\ce{Ag2CO3(s)}\)_, \(\ce{NaNO3(aq)}\)    | _\(\ce{Ag2S(s)}\),_  \(\ce{Ca(NO3)2(aq)}\) | _\(\ce{AgOH(s)}\)_, \(\ce{NH4NO3(aq)}\)       |
|-------------------------------------+-------------------------------------------+------------------------------------------+---------------------------------------------|
| \(\ce{BaBr2(aq), KCl(aq)}\)         | \(\ce{NaCl(aq)}\), _\(\ce{BaCO3(s)}\)_      | \(\ce{CaCl(aq), BaS(aq)}\)               | \(\ce{Ba(OH)2(aq), NH4Cl(aq)}\)             |
|-------------------------------------+-------------------------------------------+------------------------------------------+---------------------------------------------|
| \(\ce{AlBr3(aq), KNO3(aq)}\)        | _\(\ce{Al2(CO3)3(s)}\),_ \(\ce{NaNO3(aq)}\) | \(\ce{AlBr3(aq)}\), _\(\ce{Al2S3(s)}\)_    | _\(\ce{Al(OH)3(aq)}\),_ \(\ce{NH4NO3(aq)}\)   |
|-------------------------------------+-------------------------------------------+------------------------------------------+---------------------------------------------|
| \(\ce{K2SO4(aq), CuBr2(aq)}\)       | _\(\ce{CuCO3(s)}\),_ \(\ce{NaSO4(aq)}\)     | \(\ce{K2SO4(aq)}\), _\(\ce{CuS(s)}\)_      | \(\ce{NH4(SO4)2(aq)}\), _\(\ce{Cu(OH)2(s)}\)_ |
|-------------------------------------+-------------------------------------------+------------------------------------------+---------------------------------------------|

* Name the following, then draw the Lewis Structure for the following hydrocarbons from their full names.
#+attr_latex: :options [a.]
1. \(\ce{CH4}\) - methane
   Since the compound contains one carbon atom (meth) and there are sigma bonds
   (ane), the name of this compound is methane. From the diagram we can see the
   molecular formula is    \(\ce{CH4}\)
2. \(\ce{C3H8}\) - propane
   Since the compound has three carbon atoms (prop) and there are sigma bonds
   (ane), the name of the compound is propane. With the help of the diagram, we
   can see the molecular formula is    \(\ce{C3H8}\)
3. \(\ce{C4H8}\) - 1-butene
   Since the compound contains four carbon atoms (but) and central double bond
   (ene), the name of the compound is 1-butene. With the help of the lewis
   diagram the molecular formula is \(\ce{C4H8}\)
4. \(\ce{C4H8}\) - 2-butene
   Since the compound contains four carbon atoms (but) and a central double bond
   (ene), the name of this compound is 2-butene. The arrangement is different
   than 1-butene, hence the $2-$ at the start of the name

** Draw Lewis Structures for the following
#+attr_latex: :options [a.]
1. Ethane \(\ce{C2H}\)
   Based on the name, there are two carbon atoms and sigma bonds are present.
   The lewis diagram would be
2. Methane \(\ce{CH4}\)
   Based on the name, there should be one carbon atom and sigma bonds are
   present. The lewis diagram would be
3. Propyne \(\ce{C3H4}\)
   Based on the name, there shold be three carbon atoms and a triple bond. The
   lewis diagram woudl be
4. 2 Butene \(\ce{2C4H8}\)
   Based on the name, there shuold be four carbon atoms and a double bond. The 2
   in front signifies this is an isomer of butene. It's lewis diagram would be
