#+OPTIONS: toc:nil

225 St. Pauls Ave

Jersey City, NJ 07306

(201) 477-8773

shaunsing0207@gmail.com

Shaurya Singh

** Branding Statement
High achieving and creative student with extensive robotics design and development experience.

** Resume Objective
Student interested in science research and robotics development, seeking to apply for a research and development role in the field of robotics-based surgery. Possess strong programming and robot design skills. Honors student in mathematics and science.

** EDUCATION
McNair Academic High School - Jersey City, NJ, Rising Sophomore

GPA: 4.0
Relevant coursework -
1. Honors Geo,
2. Alg2,
3. AP Chem
4. AP CSP

** EXPERIENCE

*** McNair Robotics, Jersey City — Lead Programmer and Outreach Manager
September 2020 - PRESENT
Planned and Managed a 150+ student outreach event, teaching kids programming and robotics design.
Took part in designing and programming the robot

*** MMUN, NYC — Spokesperson
2019 - 2020
Directed multiple discussions about civil rights topics, related to deforestation in 3rd world nations, and presented our research and findings to a 1k+ audience in NYC, consisting of multiple United Nations representatives.

*** JC Citywide STUCO, Jersey City — treasurer
2018-2020
Led school body to successfully fundraise and organize large-scale annual school events.

** EXTRACURRICULARS
1. Robotics - Programming Lead
2. Model UN - Previous Speaker and Representative
3. McMed Club - Committee member
4. Science Research

** AWARDS
1. Perfect Math PSAT, Near-perfect reading/writing
2. Science Fair Finalist
3. CoderZ Virtual Robotics State Finalist
4. Head of Award-Winning A1 robotics team
5. 2 Year experience at Proyecto Science (full scholarship)
6. Completed and graduated a course from John Hopkins University
7. 4.0 GPA student at MAHS
