#+title: Ap Chem Summer Assignment #2
#+author: Shaurya Singh
#+startup: preview
#+startup: fold
#+options: toc:1
#+latex_header: \usepackage{chemfig}
#+latex_header: \usepackage[version=4]{mhchem}


* Summer Assignment 2
** What is the charge on the following:
1. The cation in $\ce{CsCl}$ has a charge of 1+, with $\ce{Cs}$ being the cation.
2. The sulfate ion has a charge of 2-
3. The barium ion has a charge of 2+
4. The nitrate ion has a charge of 1-

** How many protons, neutrons, and electrons are in:
1. Uranium-235 has *92 protons*, since it has an atomic number of 92. It also has *143 neutrons*, since $235-92=143$. Lastly, it has *92 electrons*, since it has no charge so the number of protons must equal the number of electrons.
2. Uranium-238 has *92 protons*, since it has an atomic number of 92. It also has *146 neutrons*, since $238-92=146$. Lastly, it has *92 electrons*, since it has no charge so the number of protons must equal the number of electrons.

** Elements in the same vertical column in the periodic table have similar what?
Elements in the same vertical column in the periodic table will be in the same group. Therefore, they will have the same amount of valence electrons.

** An element “E” is present as 10 E with a mass value of 10.01 amu, and as 11 E with a mass value of 11.01 amu. The natural abundances of 10 E and 11 E are 19.78% and 80.22% respectively. What is the average atomic mass of the element? What is the element?
In order to calculate the average atomic mass of the element, we must take the weighted average of the two isotopes against their percentage abundance. Multiplying that out, we get
\begin{align*}
x=(10.01*0.1978)+(11.01*0.8022)
\end{align*}
 Where x is the average atomic mass. Solving for x we get
\begin{align*}
x=10.8122
\end{align*}
 Since we must round to 4 significant figures, the correct answer is
\begin{align*}
x\approx10.81
\end{align*}
Therefore, the element has an average atomic mass of *10.81 amu*. Looking at the periodic table, the element with an average atomic mass of 10.81 is *Boron*.

** Naturally occurring sulfur consists of four isotopes, 32 S (95.0%), 33 S (0.76%), 34 S(4.22%), and 36 S(0.014%). Using this data, calculate the atomic weight of naturally occurring sulfur. The masses of the isotopes are given in the table below.
In order to calculate the atomic weight of Sulfur, we must take the weighted average of the 4 isotopes against their percentage abundance. Multiplying that out, we get
\begin{align*}
x=(31.97*0.950)+(32.97*0.0076)(33.97*0.0422)+(35.97*0.00014)
\end{align*}
Where x is the atomic weight. Solving for x we get
\begin{align*}
x&=30.373 + 0.251 + 1.433 + 0.005\\
&=30.7357392814
\end{align*}
Since we must round to 5 significant figures, the correct answer is
\begin{align*}
x\approx32.062
\end{align*}
Therefore, the element has an atomic weight of *32.062 amu*.

** Explain each of the following:
    1. Alpha radiation penetrates a much shorter distance into a piece of material than does beta radiation of the same energy.
       a. This is because when nucleons are combined in nuclei, some of their mass is converted into energy, which is called binding energy. This energy is released and stabilizes the nucleus
    2. Define the word isotope. Distinguish between isotope and isomer. Describe the differences between alpha, beta, and gamma particles.
       a.  An isotope in chemistry is two or more forms of the same element that contain equal numbers of protons but different numbers of neutrons in their nuclei. They differ in atomic mass, but share similar chemical properties
       b. An isomer is two or more compounds with the same formula but a different arrangement of atoms in the molecules. Unlike isotopes, isomers have different properties.
       c. Alpha particles are fully ionized helium nuclei, ejected by the decay of a radioactive isotope atom. Beta Particles are highly energetic electrons or positrons ejected by the decay of a neutron or proton in a radioactive isotope atom. Gamma radiation comprises of highly energetic photons above the x-ray energy range that may arise in nuclear decay
    3. Nuclear fusion requires large amounts of energy and to get started, whereas nuclear fission can occur spontaneously, although both processes release energy.

** How many moles are in a sample of 300 atoms of Nitrogen (N)? How many grams?
One mole contains $6.022 *10^{23}$ atoms, or Avogadro's number. As a result, 300 atoms of nitrogen contain:
\begin{align*}
n&=300\ atoms\\
&=\frac{300}{6.022*10^{23}}\ atoms/mol\\
&=4.98*10^{-22}\ mol
\end{align*}
Therefore, there are $4.98*10^{-22}\ mol$ in 300 atoms of Nitrogen. Since 1 mol = 1 gram, 300 atoms of Nitrogen have a mass of $4.98*10^{-22}\ g$.

** A sample of sulfur (S) has a mass of 5.37 g. How many moles are in the sample? How many atoms?
Sulfur has a molar mass of 32amu. Therefore, it has a molar mass of
$32\frac{g}{mol}$.
With that information we can make the following equation:
\begin{align*}
\frac{5.37g}{32g/mol}&=0.1678mol\\
&\approx0.17mol
\end{align*}
To convert that to atoms, we can use Avogadro's number ($6.022 *10^{23}$).
\begin{align*}
x&=(6.022*10^{23})*(0.17)\\
&=1.02374*10^{23}\\
&\approx1.0*10^{23}
\end{align*}

** How many grams of zinc are in 1.16 x 10 22 atoms of zinc (Zn)?
$149100885.37375763$ or $149000000$

** Calculate the number of grams per mole (gfm) for each of the following:
   a. $\ce{CuSO4}$
    To find the molar mass of $\ce{CuSO4}$, we must take the molar mass of
    each element in the molecule, and add it together.

    $\ce{Cu}$ (Copper) has a molar mass of 63.546 g/mol.

    $\ce{S}$ (Sulfur) has a molar mass of 32.065 g/mol.

    $\ce{O}$ (Oxygen) has a molar mass of 16 g/mol. Since we have 4 oxygen
    atoms, the actual molar mass would be $16*4=64$ g/mol

    Combining the molar mass of the 3 elements, we get

    \begin{equation}
    63.546+64+32.065=159.611\ g/mol
    \end{equation}
    With 4 significant figures, the answer is *$159.6\ g/mol$*.

   b. $\ce{NH4OH}$
    To find the molar mass of $\ce{NH4OH}$ we must take the molar mass of each element in the molecule, and add it together.

    $\ce{N}$ (Nitrogen) has a molar mass of 14.0067 g/mol.

    $\ce{O}$ (Oxygen) has a molar mass of 15.9994 g/mol.

    $\ce{H}$ (Hydrogen) has a molar mass of 1.00794 g/mol. Since we have 5
    Hydrogen molecules, that means the molar mass for this element will be
    $1.0088*5=5.0397\ g/mol$.

    Combining the molar mass of the 3 elements, we get

    \begin{equation}
    14.0067+15.9994+1.00794=35.04580\ g/mol
    \end{equation}
    With 6 significant figures, the answer is *$35.046\ g/mol$*

   c. $\ce{NH4OH}$
    To find the molar mass of $\ce{NH4OH}$ we must take the molar mass of each element in the molecule, and add it together.

    $\ce{N}$ (Nitrogen) has a molar mass of 14.0067 g/mol.

    $\ce{O}$ (Oxygen) has a molar mass of 15.9994 g/mol.

    $\ce{H}$ (Hydrogen) has a molar mass of 1.00794 g/mol. Since we have 5
    Hydrogen molecules, that means the molar mass for this element will be
    $1.0088*5=5.0397\ g/mol$.

    Combining the molar mass of the 3 elements, we get

    \begin{equation}
    14.0067+15.9994+1.00794=35.04580\ g/mol
    \end{equation}
    With 6 significant figures, the answer is *$35.046\ g/mol$*

** How many moles of cadmium bromide ($\ce{CdBr2}$) are in a 39.25 g sample?
For this we can use Avogadro's number. One mole contains $6.022*10^{23}$ particles. From that we get the following
\begin{align*}
&N = molar\ mass\\
&No = 272.219\\
&n = moles\\
&n=\frac{N}{No}
\end{align*}
Therefore, we can get
\begin{align*}
n&= \frac{39.25}{272.219}\\
&=0.144185380153\\
&\approx0.144
\end{align*}
Rounding to 4 significant figures, there will be $0.144$ moles of cadmium bromide in a 39.25 g sample

** $\ce{CH3CH2OH}$ boils at 78 °C and $\ce{CH3OCH3}$ boils at - 24 °C, although both compounds have the same composition. This difference in boiling points may be attributed to a difference in
The answer is D. Hydrogen bonding. The extra hydrogen bonds of $\ce{CH3CH2OH}$ make it harder to separate molecules, as more heat and energy is required, resulting in a higher boiling point compared to $\ce{CH3OCH3}$

** Which of the following elements has the smallest ionization energy? Explain.
Ionization energy decreases down a group, and increases from left to right across a period. Therefore, Potassium has the smallest ionization energy

** Which of the following represents the ground state electron configuration for the Mn 3+ ion? (Atomic number Mn = 25) (Hint: first write the e - config of Mn atom, then try the Mn 3+ ion.)
The electron configuration for $\ce{Mn}$ is $\ce{1s^2 2s^2 2p^6 3s^2 3p^6 3d^5 4s^2}$. The 3+ ion will have 3 fewer electrons, since a positive charge indicates more protons than electrons. Therefore, the electron configuration of $\ce{Mn^{3+}}$ is $\ce{1s^2 2s^2 2p^6 3s^2 3p^6 3d^4}$, and the correct option is *A*

** Which of the following represents an excited state?
Option *D*, $\ce{1s^2 2s^2 2p^6 3s^2 3p^6 3d^4 4s^2}$ is in an excited state, as it skips the final electron in the 3d orbital.

** The table above shows the first three ionization energies for atoms of four elements from the third period of the periodic table. Answer the following questions.
a. What is the chemical symbol for element 3, explain your reasoning.
    The third element is $\ce{Mg}$, or Magnesium. It has low first and second ionization energies relative to the third, which means it has two valence electrons. Magnesium is the element with two valence electrons in the third period of the periodic table

b. Write the complete electron configuration of element 3.
    $\ce{Mg}$ has an atomic number of 12, therefore the electron configuration of Magnesium is $\ce{1s^2 2s^2 2p^6 3s^2}$

c. What is the chemical symbol for element 2 and what is the expected ion charge for its most common ion?
    The symbol for element 2 is $\ce{Na}$, and the expect ion charge for its most common ion is 1+.

d.  A neutral atom of which of the four elements above has the smallest radius? Write the symbol for this element and explain this using the first ionization values given.
   Element 1, Atomic radius has a trend from right to left across a period, while ionization energy has a trend from left to right across a period. Since element 1 has the highest ionization energy, it would have the smallest atomic radius

e. Which would have a higher electronegativity, element 1 or 4? Briefly explain.
   Element 1 would have a higher electronegativity. Both electronegativity and ionization energy follow the same trend, this means that the element with the higher ionization energy will have a higher electronegativity. In this case, that is element 1.

f. The elements are $\ce{Cl}$, $\ce{Na}$, $\ce{Mg}$, and $\ce{S}$ respectively.

** Calculate the mass percent of $\ce{Cl}$ in each of the following compounds
1. $\ce{Cl}$  has a Mass Percent of $7.6059$ in $\ce{CIF}$
2. $\ce{Cl}$  has a Mass Percent of $51.7866$ in $\ce{HClO2}$
3. $\ce{Cl}$  has a Mass Percent of $52.7370$ in $\ce{CuCl2}$

** Calculate the mass percent of each element in $\ce{Ba(OH)2*8H2O}$, or barium hydroxide octahydrate
1. $\ce{Ba}$  has a Mass Percent of $43.5318$ in $\ce{Ba(OH)2*8H2O}$,
2. $\ce{H}$  has a Mass Percent of $5.7512$ in $\ce{Ba(OH)2*8H2O}$,
3. $\ce{O}$  has a Mass Percent of $50.7171$ in $\ce{Ba(OH)2*8H2O}$,

** A compound is found, by mass spectral analysis, to contain the following percentages of elements by mass, C = 49.67%, Cl = 48.92%, H = 1.39%, The molar mass of the compound is 289.9 g/mole. Determine the empirical and molecular formulas of the compound.
\begin{align*}
&C:\ \frac{49.67g}{1}\times\frac{1mol\ce{S}}{12.01g}=4.135mol\\
&Cl:\ \frac{48.92g}{1}\times\frac{1mol\ce{Cl}}{35.453g}=1.380mol\\
&H:\ \frac{1.39g}{1}\times\frac{1mol\ce{H}}{1.008g}=1.380mol\\
&E.F.M.=(3)12.011g+35.453g+1.008g=72.494g
\end{align*}
From that we can calculate the following ratios:
\begin{align*}
&\frac{4.135mol}{1.380mol}=3\\
&\frac{1.380mol}{1.380mol}=3\\
&\frac{1.380mol}{1.380mol}=3
\end{align*}
 Since $\ce{C}$, $\ce{Cl}$, and  $\ce{H}$ have a ratio of $3:1:1$, the molecular formula will be $\ce{(C3ClH)_n}$ To calculate the empirical formula we solve for n
\begin{align*}
n&=\frac{289.9g}{72.494g}\\
&=4
\end{align*}
Therefore, we can substitute 4 for n.
\begin{align*}
\ce{(C3ClH)_n}&=\ce{(C3ClH)4}\\
&=\ce{C12Cl4H4}
\end{align*}

** Determine the empirical formula of a compound that contains the following percentages of elements by mass: Mo = 43.95%, O = 7.33%, Cl = 48.72%
$\ce{Cl3MoO}$

** Aspartame is an artificial sweetener used in food and beverages that is 160 times sweeter than sucrose.
1. Using the molecular structure, determine the molecular formula of aspartame, using this format $\ce{C_{W}H_{X}N_{Y}O_{Z}}$
   There are 17 hydrogen atoms, 14 Carbon atoms, 2 Nitrogen atoms, and 5 Oxygen atoms. Therefore, the answer would be $\ce{C14H17N2O5}$
2. How many molecules are present in 10.0 mg of aspartame? How many hydrogen atoms? O atoms?
    $14\times6+17\times1+2\times7+5\times8=283\frac{g}{mol}$
    \begin{align*}
    mol&=\frac{g}{g/mol}\\
    mol&=\frac{10g}{283g/mol}\\
    mol&=035
    \end{align*}
    Therefore, there are $0.035mol$ of aspartame in 10 grams
    Multiplied by Avogadro's number, that's $2.0475*10^{22}$ molecules.

** Watch the following video on making a solution and how to calculate molarity:
1. Describe how you would make 100.0 mL of a 1.0 M solution of lithium chloride.
We have a $1.0M$ solution, which translates to  a $1.0mol/L$
We need to find the value for $100ml$, or $0.1L$
$y = 100mL = 0.1L$
We can plug that into this equation, and solve for x
\begin{align*}
x&= M * y(mol/L) * LiCl\frac{g}{mol}\\
&1.0 * 0.1(mol/L) * 42.394\frac{g}{mol}\\
&0.1mol * 42.394\frac{g}{mol}\\
&4.2394g\\
\end{align*}
Therefore, in order to get 100mL of lithium chloride, we must need 4.2394g of lithium chloride
1. First we must get our lithium chloride.
2. Afterwards, using our electronic balance, lab scoop, and weighing paper we can measure out 4.2394g of LiCl.
3. Once we calculate that out, we can use a 100.0mL volumetric flask to measure it.
4. Since the molarity is $1.0mol/L$, 100% of the solution is $\ce{LiCL}$, and no water is required.
