#+title: What is Ocean Acidification
#+subtitle:Chapter #2
#+author: Shaurya Singh
#+startup: preview
#+startup: fold
#+options: toc:2
#+latex_class: chameleon
#+latex_header: \usepackage{siunitx}
#+latex_header: \usepackage{mhchem}
#+latex_header: \usepackage{chemfig}
#+latex_header: \DeclareSIUnit{\pH}{pH}

* How are fossil fuels related to ocean acidification?
The driving force for ocean acidity are fossil fuels. THe $\ce{CO2}$ released into the atmosphere raises the global temperature but 25% of that also gets asborbed into oceans.
* Why weren’t scientists initially concerned that the ocean absorbs excess carbon dioxide?
Initially scientists believed that this was beneficial since more $\ce{CO2}$ in the ocean means less in the air, reducing the warming effect. Scientists soon realized that the extra $\ce{CO2}$ absorbed by the ocean is changing the waters chemistry, driving down the \(\SI{}{\pH}\).
* Describe how carbonic acid is formed in the ocean.
$\ce{CO2}$ Reacts with \(\ce{H2O}\) to form the week acid carbonic acid. This immediately breaks apart, releasing hydrogen ions increasing water's acidity
* How are oysters affected by decreased availability of carbonate in the water?
Healthy baby oysters pull in the ingredients they need from the surrounding water, to form Calcium Carbonate which forms their shell. However, sometimes too much carbon dioxide is pulled into the mix. The floating hydrogen ions react with the carbonate and therefore less carbonate is available, making it harder for oysters to make their shell and killing them.
* Besides oysters, what other animals do you think might be in danger from ocean acidification?
Any other shelled animals, such as mussels, clams, urchins, and starfish, are all going to have trouble building their shells in more acidic water, as just like oysters, they are going to die trying to find carbonate.
