#+title: Effect of common diabetic drug metformin on the aging process.
#+subtitle: Science Research: Intro #1
#+author: Shaurya Singh
#+startup: preview
#+startup: fold
#+options: toc:2
#+latex_header: \usepackage{chemfig}
#+latex_header: \usepackage[version=4]{mhchem}
#+latex_header: \usepackage{enumerate}

* Proposal
Diabetes is becoming one of the most widespread health burning problems in the elderly. Worldwide prevalence of diabetes among subjects over 65 years was 135.6 million in 2019, a number that is expected to double in 2045. Over 34 million Americans have diabetes, and over 88% of diabetic Americans take oral medications and insulin to treat and control it. While these drugs suppress type 2 diabetes, previous studies have shown a link between such drugs and (de)accelerated aging. Of these drugs, metformin is the most prevalent. In this study I will utilize the zebrafish model to test the effect of metformin on the aging process in a healthy individual. Zebrafish, who have a similar genetic structure to humans, will be subjected to metformin for different times and doses. The resulting zebrafish DNA will be assessed for DNA damage, and the resulting RNA will be assessed for damage on DNA repair genes such as PARP1 (Poly[ADP-Ribose]Polymerase 1) and PCNA (Proliferating Cell Nuclear Antigen). Such research will help us further improve our understanding of the aging of the human body in the long-term.

* Method
1. Acquire zebrafish aged 6-15 months from Zebrafish International Resource Center (ZIRC; University of Oregon, Eugene, OR, USA). Maintain fish at 28\pm1 \deg C. Water is changed twice a week, zebrafish are fed 120 mg per fish per day of a commercially available fish food, divided over six day feedings using an automated feeding system. #_ Zebrafish are each contained in __L tanks
2. Zebrafish are anesthetized in water containing 0.05% ethyl 3-aminobenzoate methanesulfonate (MS-222 or tricaine; E10521, Sigma-Aldrich).
3. Going to take 2 Drugs. Each drug will have 5 fish per time/dose
   - +No drug+
   - Drug
   - Vehicle
   - +postive/negative controls+
4. Asses DNA damage;
   - Isolate DNA
   - Run it on agarose gel to isolate DNA
   - Run under ethidium bromide + UV Light (+buffer to maintain enviornment)
   - Check for streaks/damage/etc with ladder
5. Asses DNA Repair Mechanisms
   - Transcribe/Isolate RNA
   - Two step (cDNA, primer, operate on cDNA) OR One step (cDNA+primer \Rightarrow 3`/5` 5`/3`)
   - Focus on repair genes i.e. PARP1 and PCNA
   - Find Primer:
     a. mRNA sequence \Rightarrow CDS
     b. Blast
   - PCR process to amplify Signal

* Supplies/Cost
Contact:
| Supply                                 | Cost ($) | Notes |
|----------------------------------------+----------+-------|
| Eppendorf Tube                         | x        |       |
| EDTA (Ethylenediaminetetraacetic acid) |          |       |
| Triton X-100                           |          |       |
| Proteinase K                           |          |       |
| \(\ce{C2H6O}\) Ethanol                 | x        |       |
| Agarose gel                            | x        |       |
| Ladder + Loading Buffer                |          |       |
| UV Light                               | x        |       |
| Ethidium Bromide                       |          |       |
| Micro Pipettes                         | x        |       |
| *Subtotal*                               | $500-750 |       |

| Supply                                 | Cost ($) | Notes |
|----------------------------------------+----------+-------|
| Inhibitors                             |          |       |
| Zebrafish                              |          |       |
| Zebrafish maintainence                 |          |       |
| *Subtotal*                               |          |       |
| *Total*                                  |          |       |

Notes:
Check if PCR machine is working
