#+title: Ap CSP Summer Assignment
#+author: Shaurya Singh
#+startup: fold
#+startup: preview
#+options: toc:2

* Chapter 1: Digital Explosion
** Vocabulary
1. Word: bit

   Definition: (n) *bit* (a unit of measurement of information (from binary + digit); the amount of information in a system having two equiprobable states) "there are 8 bits in a byte"

   Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=bit&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 18 July 2021.

2.  Word: koan

    Definition: (n) *koan* (a paradoxical anecdote or a riddle that has no solution; used in Zen Buddhism to show the inadequacy of logical reasoning)

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=koan&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 18 July 2021.

3.  Word: ping

    Definition: (v) *ping* (send a message from one computer to another to check whether it is reachable and active) "ping your machine in the office"

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=Ping&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 23 July 2021.

4.  Word: benign

    Definition: (adj) *benign* (not dangerous to health; not recurrent or progressive (especially of a tumor))

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=benign&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

5.  Word: utopian

    Definition: (n) *utopian* (an idealistic (but usually impractical) social reformer) "a Utopian believes in the ultimate perfectibility of man"

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=utopian&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

6.  Word: err

    Definition: (v) *err*, mistake, slip (to make a mistake or be incorrect)

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=err&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

7.  Word: paradoxically

    Definition: (adv) *paradoxically* (in a paradoxical manner) "paradoxically,  ice ages seem to occur when the sun gets hotter"

   (adj) *paradoxical*, self-contradictory (seemingly contradictory but nonetheless possibly true) "it is paradoxical that standing is more tiring than walking"

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=paradoxically&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

8.  Word: expunge

    Definition: (v)  *expunge* (remove by erasing or crossing out or as if by drawing a line)

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=expunge&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

9.  Word: database

    Definition: (n) *database* (an organized body of related information)

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=database&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

10. Word: blacklist

    Definition: (v) *blacklist* (put on a blacklist so as to banish or cause to be boycotted) "many books were blacklisted by the Nazis"

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=blacklist&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

** Ideas:
1. Companies keep records of cellphone locations (Page 1)
2. "Its all just bits" (Page 5)
3. "In fact, processors have hardly grown faster at all" (Page 8)
4. "By 2011, we may be producing more bits than we can store" (Page 10)

** Journal Entry
1. I support the idea of companies keeping track of cellphone locations, as long
   as that information is kept private and in the hands of only the government.
   Cellular locations are incredibly useful for finding missing people, and
   quickly reacting to emergencies, such as in Tanya's case.

   However, the key term is /as long as that information is kept private and in
   the hands of the government/. Private companies shouldn't be able to get the
   locations of users. These locations are often sold to advertising firms.
   Companies like Cuebiq make money by collecting location data from smartphone
   users who agree to share their locations for weather or maps, then analyse
   and sell that data to advertisers and marketers. Location data shouldn't be  used to target people, and should be used as a last resort

2. While technically it is all just bits, personally I believe we shouldn't
   think of it as such. Thinking of computers in terms of bits is like thinking
   of writing in terms of atoms on a piece of paper. While all handwritten work
   is technically just graphite on paper, we interpret it as much more than
   that. We think of writing in terms of words, phrases, paragraphs, and should
   think of the computer experience in terms of experiences. Similarly,
   copyright law is based on text, and so laws pertaining to computers should be
   based on the end user's experience, not what delivers that experience

3. Considering the next sentence is talking about "multiple processors on the
  same chip" I assume this statement is talking about the processor cores
  themselves. However, data shows that the fastest processors today are about
  80 times faster in terms of single core performance with the same efficiency.
  Still, its true that processor cores have increased over the years (from
  single core chips to server chips with over 128 cores in the span of just 20
  years).

  In my opinion we should focus more on processor efficiency and less on raw
  processor speed. Processor's these days, even budget ones, are more than fast
  enough for the majority of use cases. The market for large, high end HEDT
  processors is extremely small compared to the market share of their lower end
  counterparts. The future is about switching to arm-based processors in
  laptops, which should give much more performance at the same wattage.

4. I found this statement the most interesting in this chapter. We've made leaps
   and bounds in storage technology since then, nowadays you can buy tens of
   terabytes of storage for quite cheap, compared to the expensive "high end"
   80gb drives you could get in 2008, back when this textbook
   released.

   Similar my opinion on processor speed, instead of focusing on storage size
   and how much data we can store, we should talk about how we store data.
   Companies are moving to cloud-based centralized storage, and as of 2020 50%
   of all corporate data is stored in the cloud, up from 30% just 5 years
   earlier. As more and more people start using cloud services (e.g. OneDrive,
   iCloud, Google Drive), we should focus on make data transfer to and from
   those drives quicker and more secure.

* Chapter 2: Naked in the Sunlight
** Vocabulary
1. Word: pervasive

   Definition: per·va·sive | pərˈvāsiv | adjective (especially of an unwelcome influence or physical effect) spreading widely throughout an area or a group of people: ageism is pervasive and entrenched in our society.

   Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=pervasive&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 18 July 2021.

2.  Word: cleric

    Definition: cler·ic | ˈklerik | noun a priest or religious leader, especially a Christian or Muslim one.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=cleric&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 18 July 2021.

3.  Word: disseminate

    Definition: dis·sem·i·nate | dəˈseməˌnāt | verb [with object ] spread (something, especially information) widely: health authorities should foster good practice by disseminating information.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=disseminate&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 23 July 2021.

4.  Word: encode

    Definition: en·code | inˈkōd, enˈkōd | verb [with object ] convert into a
   coded form: using this technique makes it possible to encode and transmit recorded video information.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=encode&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

5.  Word: RFID

    Definition: RFID *(abbreviation)* radio frequency identification, denoting
   technologies that use radio waves to identify people or objects carrying encoded microchips.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=RFID&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

6.  Word: exonerate

    Definition:  ex·on·er·ate | iɡˈzänəˌrāt | verb [with object ] 1 (especially of an official body) absolve (someone) from blame for a fault or wrongdoing, especially after due consideration of the case: they should exonerate these men from this crime

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=exonerate&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

7.  Word: discourse

    Definition: noun | ˈdisˌkôrs | written or spoken communication or debate: an imagined discourse between two people
   traveling in France.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=discourse&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

8.  Word: profilerate

    Definition: (v)  *profilerate* increase rapidly in numbers; multiply.

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=profilerate&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

9.  Word: prodigious

    Definition: pro·di·gious | prəˈdijəs | adjective, remarkably or impressively great in extent, size, or degree: the stove consumed a prodigious amount of fuel.

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=prodigious&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

10. Word: clairvoyant

    Definition: clair·voy·ant | ˌklerˈvoiənt | noun a person who claims to have a supernatural ability to perceive events in the future or beyond normal sensory contact

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=clairvoyant&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

** Ideas:
1. The notion of privacy has become fuzzier at the same time as the
   secrecy-enhancing technology of encryption has become widespread (Page 21)
2. His car had a black box-an EDR, that captured every detail about what was
   going on before the crash (page 27)
3. Bits mediate our daily lives. It is almost as hard to avoid leaving digital
   footprints as it is to avoid touching the ground when we walk
4. "There is no patient confidentiality" said Dr. Joseph Heyman. "It's gone"

** Journal Entry
1. I agree with the notion that privacy has become fuzzier over time. As
   encryption and security technologies are becoming more widespread, it seems
   people are caring less and less about their privacy when really they should
   be caring more. Companies give us a false sense of privacy, when really they
   are breaching it more than ever.

   The greatest example of this is google. When you open up www.google.com, you
   can see multiple mentions of privacy. In reality, google is notorious for
   using user information to target ads and search results. They have multiple
   analytics and adsense services that companies can purchase.

2.  I agree with the idea of having tracking devices in cars. If most people are
   given the choice between getting an expensive ticket and facing criminal
   charges or lying, most people will choose to lie. Devices like the EDR ensure
   we can make a conclusion based on actual data rather than from the victims
   point of view.

   However, similar to the issue with cellphone locations  the key term is /as
   long as that information is kept private and in the hands of the government/.
   Private companies shouldn't be able to get the locations of users and use it
   when it isn't needed. Examples of this can be determining how to price
   billboard advertising, requiring cars to be serviced ever /x/ miles.  There can
   be certain exceptions (e.g. An insurance company trying to determine who is
   at fault), but for the most part this information should be for the
   government, and even then only for when the government absolutely requires it

3. Its true that now its extremely difficult to do anything without leaving
   digital traces everywhere. I personally think this issue is linked to idea
   #1, people value convenience over privacy. Companies create a false sense of
   privacy, and justify all the analytics with improved convenience.

   Most people don't want to put effort into maintaining their privacy, or
   resist changes to their workflow and life .

4.

* Chapter 3: Ghosts in the Machine
** Vocabulary
1. Word: pervasive

   Definition: per·va·sive | pərˈvāsiv | adjective (especially of an unwelcome influence or physical effect) spreading widely throughout an area or a group of people: ageism is pervasive and entrenched in our society.

   Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=pervasive&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 18 July 2021.

2.  Word: cleric

    Definition: cler·ic | ˈklerik | noun a priest or religious leader, especially a Christian or Muslim one.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=cleric&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 18 July 2021.

3.  Word: disseminate

    Definition: dis·sem·i·nate | dəˈseməˌnāt | verb [with object ] spread (something, especially information) widely: health authorities should foster good practice by disseminating information.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=disseminate&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=. Accessed 23 July 2021.

4.  Word: encode

    Definition: en·code | inˈkōd, enˈkōd | verb [with object ] convert into a
   coded form: using this technique makes it possible to encode and transmit recorded video information.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=encode&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

5.  Word: RFID

    Definition: RFID *(abbreviation)* radio frequency identification, denoting
   technologies that use radio waves to identify people or objects carrying encoded microchips.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=RFID&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

6.  Word: exonerate

    Definition:  ex·on·er·ate | iɡˈzänəˌrāt | verb [with object ] 1 (especially of an official body) absolve (someone) from blame for a fault or wrongdoing, especially after due consideration of the case: they should exonerate these men from this crime

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=exonerate&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

7.  Word: discourse

    Definition: noun | ˈdisˌkôrs | written or spoken communication or debate: an imagined discourse between two people
   traveling in France.

    Ref: WordNet Search - 3.1. http://wordnetweb.princeton.edu/perl/webwn?s=discourse&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

8.  Word: profilerate

    Definition: (v)  *profilerate* increase rapidly in numbers; multiply.

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=profilerate&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

9.  Word: prodigious

    Definition: pro·di·gious | prəˈdijəs | adjective, remarkably or impressively great in extent, size, or degree: the stove consumed a prodigious amount of fuel.

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=prodigious&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

10. Word: clairvoyant

    Definition: clair·voy·ant | ˌklerˈvoiənt | noun a person who claims to have a supernatural ability to perceive events in the future or beyond normal sensory contact

    Ref: WordNet Search - 3.1.
    http://wordnetweb.princeton.edu/perl/webwn?s=clairvoyant&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=0000000. Accessed 23 July 2021.

** Ideas:
1.
2.
3.
4.

** Journal Entry
1.
2.
3.
4.
