:PROPERTIES:
:ID:       b66ee28b-972d-43f2-a9b0-9d5b5937ce18
:END:
#+title: Reference Notes
The technique of grouping information, organizing ideas into categories, and
creating tags to help you find grouped information at a later stage is the art
of reference notes. When we reference something, it is safe to say that the
topic or idea we are writing about is part of a bigger topic or is information
accredited to someone or someplace else. We use this technique in various daily
circumstances and the function is available on almost every software and app
available today.

Common ways we use referencing in everyday life include the use of the hashtag (#) on social networking platforms, attributing credit when writing a thesis paper, or when adding a hyperlink to the source location of a particular referenced media file such as pictures, GIFs, or videos. Using a search engine when interested in a particular keyword and tagging others or replying to messages in chat apps also constitute referencing. Helpful ways to mark reference notes include applying a hashtag when using digital software, color coding, or including a unique ID address.
