#+title: Manifest Destiny #1
#+author: Shaurya Singh
#+startup: fold
#+options: toc:nil
#+latex_class: chameleon

* Why did Americans think they were so special?
From the wording used in the text, it appears the American's of the time thought
of themselves as the nation of /progress, individual freedom, of universal enfranchisement/. They believed that America was the work of God, and that
America has been chosen for a mission, that only we can put an end to the
tyranny of kings, as opposed to other nations who are /shut out from the live-giving of truth/. Americans believed their nation was destined to be the
greatest nation of the future, and their expansion was justified as a work of
God.

At the time, almost no nation had defended against a monarchy, and gained
independance against a power such as Britain. High of their horses, the
Americans didn't think of expansion as much more.

* Are you surprised by the reasons that O’Sullivan gives for expansion?
By modern standards, I am surprised. O’Sullivan's reasoning for expansion cannot
be proven, as it depends on God and religous ideals. He our expansion and
annexation of texas is just the fullfillment of the Manifest Destiny, and that
the opposition is /hampering our power, [and] limiting our greatness/.

On top of this, O'Sullivan is contradicting himself and sperading inaccurate
information. He mentions that our country is based on individual freedom, yet we
still have slaves. He said that we have universal enfranchisement, yet the only
people who could vote at the time were white men.

In the modern day and age, we don't justify reasoning through religious ideals,
rather we back it up with debate, science, and facts. Had a similar piece of
text been submitted to a newspaper or other work, it would be rejected
immediately.

However, by the standards back then, this isn't very surprising. In the 1800's
science and debate was close to nonexistant, and statements were based on either
religious ideals or opinions given by journalists and officials. People thought
that America was the nation created by god, and everyone followed this
religious mindset back then

* This theory that Americans are special is called “American Exceptionalism.” It’s this idea that America has had such a unique history and has become so powerful that there’s something really special about it. What do you think about this theory? Is it still present today? Explain why/why not
This issue is very much still present today, although to a lesser extent. Every
time an election nears, or a national event occurs, many justify their rash
actions through "Patriotism". Rather than back up statements with logic, many
people base it off of innacurate, opinionated news sources, as well as religious
ideals, similar to the mindset described earlier.
