#+title: The Morality Of Slavery
#+author: Shaurya Singh
#+date: 2021-10-14
#+options: toc:2
#+latex_class: chameleon

* Document 1: Thirty Dollars Reward
1. Who is the Author of this poster? The author of this poster is Ignatious
   Davis, as noted at the bottom right of the poster.
2. Who is the audience for this poster? The audience of this poster are the
   people of Frederick Town.
3. What is the purpose of this poster? The purpose of this poster is to ask the
   people of Frederick town to return Mr. Davis's slave.
4. Where or when will this event take place? This event takes place in Frederick
   Town, in 1791.
5. How might this event influence the people who attend it? This event offers a
   cash prize for those who bring back the slave. This event promotes the idea
   of slavery, and may influence others to buy slaves as well

* Document 2: Men of Color to Arms! To Arms! Now or Never!
1. Who is the Author of this poster? The author of this poster is Ignatious
   Davis, as noted at the bottom right of the poster.
2. Who is the audience for this poster? The audience of this poster are the
   people of Frederick Town.
3. What is the purpose of this poster? The purpose of this poster is to ask the
   people of Frederick town to return Mr. Davis's slave.
4. Where or when will this event take place? This event takes place in Frederick
   Town, in 1791.
5. How might this event influence the people who attend it? This event offers a
   cash prize for those who bring back the slave. This event promotes the idea
   of slavery, and may influence others to buy slaves as well
