#+title: Ap Chem Summer Assignment #2
#+author: Shaurya Singh
#+startup: preview
#+OPTIONS: toc:nil
#+latex_header: \usepackage{chemfig}
#+latex_header: \usepackage{mhchem}

* Summer Assignment 2
** What is the charge on the following:
1. The cation in $\ce{CsCl}$ has a charge of 1+, with $\ce{Cs}$ being the cation.
2. The sulfate ion has a charge of 2-
3. The barium ion has a charge of 2+
4. The nitrate ion has a charge of 1-

** How many protons, neutrons, and electrons are in:
1. Uranium-235 has *92 protons*, since it has an atomic number of 92. It also has *143 neutrons*, since $235-92=143$. Lastly, it has *92 electrons*, since it has no charge so the number of protons must equal the number of electrons.
2. Uranium-238 has *92 protons*, since it has an atomic number of 92. It also has *146 neutrons*, since $238-92=146$. Lastly, it has *92 electrons*, since it has no charge so the number of protons must equal the number of electrons.

** Elements in the same vertical column in the periodic table have similar what?
Elements in the same vertical columnn in the periodic table will be in the same group. Therefore, they will have the same amount of valence electrons.
